# Usa uma imagem oficial do Python
FROM python:3.12-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos do projeto
COPY . .

# Instala as dependências
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Cria um usuário não-root para executar a aplicação
RUN adduser --disabled-password --gecos '' appuser
# Define permissões corretas para os arquivos da aplicação
RUN chown -R appuser:appuser /app

# Expõe a porta que o Flask usa
EXPOSE 8080

# Define a variável de ambiente para produção
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8080

# Altera para o usuário não-root
USER appuser

# Comando para iniciar o Flask
CMD ["flask", "run"]
