services:
  - type: web
    name: aprovacao-lta
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      PYTHON=$(python3 -c "import sys; print(sys.executable)")
      $PYTHON src/aprovacao_lta/sql/criar_tabelas.py
      $PYTHON -m src.aprovacao_lta.sql.importar_perguntas_excel
    startCommand: gunicorn src.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aprovacao_projeto_db
          property: connectionString
      - key: SECRET_KEY
        sync: false